{
 "title": "Nginx 360 监控 Thanos",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "server",
    "label": "server",
    "query": "label_values(nginx_http_connections, hostname)"
   }
  ]
 },
 "panels": [
  {
   "title": "当前域名",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(sum(nginx_http_request_duration_seconds_count) by (host))"
    }
   ]
  },
  {
   "title": "当前并发",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(nginx_http_api_requests_latest_30s)"
    }
   ]
  },
  {
   "title": "当前错误请求",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(nginx_http_api_requests_latest_30s{status=~\"4.*|5.*\"})"
    }
   ]
  },
  {
   "title": "reading",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nginx_http_connections{state=\"reading\"}",
     "legendFormat": "{{ hostname }}"
    }
   ]
  },
  {
   "title": "waiting",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nginx_http_connections{state=\"waiting\"}",
     "legendFormat": "{{ hostname }}"
    }
   ]
  },
  {
   "title": "writing",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nginx_http_connections{state=\"writing\"}",
     "legendFormat": "{{ hostname }}"
    }
   ]
  },
  {
   "title": "Top来源域名",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 9 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(nginx_http_api_requests_latest_30s) by (host) > 10",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Top来源域名趋势",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(nginx_http_api_requests_latest_30s) by (host) > 10",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "状态码分布",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(nginx_http_api_requests_latest_30s) by (status) > 0",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "状态码趋势",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(nginx_http_api_requests_latest_30s) by (status) > 0",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "错误状态码分布",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(nginx_http_api_requests_latest_30s{status=~\"4.*|5.*\"}) by (status)",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "错误状态码趋势",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(nginx_http_api_requests_latest_30s{status=~\"4.*|5.*\"}) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "区域请求分布",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 36 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(nginx_http_api_requests_latest_30s) by (region) > 0 ",
     "legendFormat": "{{region}}"
    }
   ]
  },
  {
   "title": "区域请求趋势",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(nginx_http_api_requests_latest_30s) by (region) > 0",
     "legendFormat": "{{region}}"
    }
   ]
  },
  {
   "title": "Top 5 URL请求",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "topk(5, sum(nginx_http_api_requests_latest_30s) by (api, host))"
    }
   ]
  },
  {
   "title": "Top 5 错误URL请求",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 44 },
   "targets": [
    {
     "expr": "topk(5, sum(nginx_http_api_requests_latest_30s{status=~\"4.*|5.*\"}) by (host, api, status))"
    }
   ]
  },
  {
   "title": "区域平均响应时间",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_http_request_duration_seconds_sum[30s])) by (region)/sum(rate(nginx_http_request_duration_seconds_count[30s])) by (region)",
     "legendFormat": "{{region}}"
    }
   ]
  }
 ]
}